import { BaseModel } from './base_model';

/**
 * Created by Daniel on 19.02.2017.
 */
export class Innovation extends BaseModel {
  consequence: InnovationTag;
  tags: InnovationTag[];
  isBase: boolean;
}

export enum InnovationTag {
  ART = 'ART',
  EDUCATION = 'EDUCATION',
  FAITH = 'FAITH',
  HOME = 'HOME',
  MUSIC = 'MUSIC',
  OTHER = 'OTHER',
  SCIENCE = 'SCIENCE',
  STARTING_INNOVATION = 'STARTING_INNOVATION',
  AMMONIA_CONSEQUENCE = 'AMMONIA_CONSEQUENCE',
  DRUMS_CONSEQUENCE = 'DRUMS_CONSEQUENCE',
  FAMILY_CONSEQUENCE = 'FAMILY_CONSEQUENCE',
  FORBIDDEN_DANCE_CONSEQUENCE = 'FORBIDDEN_DANCE_CONSEQUENCE',
  HOVEL_CONSEQUENCE = 'HOVEL_CONSEQUENCE',
  INNER_LANTERN_CONSEQUENCE = 'INNER_LANTERN_CONSEQUENCE',
  LANGUAGE_CONSEQUENCE = 'LANGUAGE_CONSEQUENCE',
  LANTERN_OVEN_CONSEQUENCE = 'LANTERN_OVEN_CONSEQUENCE',
  SCULPURE_CONSEQUENCE = 'SCULPURE_CONSEQUENCE',
  SHRINE_CONSEQUENCE = 'SHRINE_CONSEQUENCE',
  STORYTELLING_CONSEQUENCE = 'STORYTELLING_CONSEQUENCE',
  SONG_OF_THE_BRAVE_CONSEQUENCE = 'SONG_OF_THE_BRAVE_CONSEQUENCE',
  SYMPOSIUM_CONSEQUENCE = 'SYMPOSIUM_CONSEQUENCE',
  PAINT_CONSEQUENCE = 'PAINT_CONSEQUENCE',
  PICTOGRAPH_CONSEQUENCE = 'PICTOGRAPH_CONSEQUENCE',
}
