import { BaseModel } from './base_model';

/**
 * Created by Daniel on 19.02.2017.
 */
export class Innovation extends BaseModel {
  consequence: InnovationTag;
  tags: InnovationTag[];
  isBase: boolean;
}

export enum InnovationTag {
  ART,
  EDUCATION,
  FAITH,
  HOME,
  MUSIC,
  OTHER,
  SCIENCE,
  STARTING_INNOVATION,
  AMMONIA_CONSEQUENCE,
  DRUMS_CONSEQUENCE,
  FAMILY_CONSEQUENCE,
  FORBIDDEN_DANCE_CONSEQUENCE,
  HOVEL_CONSEQUENCE,
  INNER_LANTERN_CONSEQUENCE,
  LANGUAGE_CONSEQUENCE,
  LANTERN_OVEN_CONSEQUENCE,
  SCULPURE_CONSEQUENCE,
  SHRINE_CONSEQUENCE,
  STORYTELLING_CONSEQUENCE,
  SONG_OF_THE_BRAVE_CONSEQUENCE,
  SYMPOSIUM_CONSEQUENCE,
  PAINT_CONSEQUENCE,
  PICTOGRAPH_CONSEQUENCE,
}
